### ISSUE TITLE
Build a docker version and add it to docker hub

### ISSUE THREAD

**Issue by ghost** [jonathanlb/sqlite32grafana#1]

**Comment by jonathanlb** [comment]
That's a nice idea! Thanks.

**Comment by jonathanlb** [comment]
@steffenix do you have guidance for user interface for a sqlite32grafana instance packaged for Docker Hub?  Starting the server requires 

- path (and access) to a sqlite3 file, presumably not in the image stored at Docker Hub...
- a table name
- a column name to order data points

**Comment by ghost** [comment]
And a port to expose the service.

**Comment by jonathanlb** [comment]
Maybe I'm misunderstaning your reply @steffenix .... I wasn't clear enough asking the question.  

There are several parameters (and file access) required to start sqlite32grafana that I'm unsure of the best way of exposing via a Docker Hub instance.  It's easy to publish a canned demo allowing someone to explore a sample sqlite DB that is baked into the container, but I don't see the benefit beyond advertising sqlite32grafana.

It would be nice if the published image had hooks to allow it to read a file specified and column names when the container is started.  I'm asking for advice on how best to do that upon start up, and I'm thinking that the existing sqlite32grafana start up interface might have to change to support the parameterization.

Currently sqlite32grafana reads those parameters from the command line.  The approach that seems most obvious is also a little clunky, error prone, and involves statefullness violating Docker principles.
 - Pass the path to the sqlite file and column names via environment variables.
 - Mount the directory containing the sqlite file from the container.
  - I'm a little concerned about sqlite locks and consistency with mounting the directory.  Mounting the file directly is unsafe.  Copying the file surely safe, in which case it seems easiest just to script creation of a Dockerfile that copies the file into the container-- the approach I've already done.
 - Write a script to start sqlite32grafana using the environment variable values.
